import { saveAs } from "file-saver";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import * as XLSX from "xlsx";

export type ShopHeader = {
  shopName: string;
  address?: string;
  phone?: string;
};

export function exportRowsToExcel(filename: string, rows: Record<string, unknown>[]) {
  const sheet = XLSX.utils.json_to_sheet(rows);
  const book = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(book, sheet, "Report");
  const buffer = XLSX.write(book, { bookType: "xlsx", type: "array" });
  saveAs(new Blob([buffer]), `${filename}.xlsx`);
}

export function exportRowsToPdf(filename: string, title: string, rows: Record<string, unknown>[], shop?: ShopHeader) {
  const doc = new jsPDF();
  let y = 14;

  if (shop) {
    doc.setFontSize(16);
    doc.text(shop.shopName, 14, y);
    y += 8;
    doc.setFontSize(10);
    if (shop.address) {
      doc.text(shop.address, 14, y);
      y += 6;
    }
    if (shop.phone) {
      doc.text(`Phone: ${shop.phone}`, 14, y);
      y += 6;
    }
    doc.text(`Generated: ${new Date().toLocaleDateString("en-IN")}`, 14, y);
    y += 10;
  }

  doc.setFontSize(12);
  doc.text(title, 14, y);
  const keys = Object.keys(rows[0] || { message: "No data" });
  autoTable(doc, {
    startY: y + 6,
    head: [keys],
    body: rows.map((row) => keys.map((key) => String(row[key] ?? ""))),
    styles: { fontSize: 8 }
  });
  doc.save(`${filename}.pdf`);
}

export type OrderListExportRow = {
  sno: number;
  category: string;
  item: string;
  quantity: number;
};

export function exportOrderListToPdf(
  rows: OrderListExportRow[],
  shop: ShopHeader,
  orderNumber?: string
) {
  const doc = new jsPDF();
  let y = 16;

  doc.setFontSize(18);
  doc.text(shop.shopName, 14, y);
  y += 8;

  doc.setFontSize(10);
  if (shop.address) {
    const addressLines = doc.splitTextToSize(shop.address, 180);
    doc.text(addressLines, 14, y);
    y += addressLines.length * 5 + 2;
  }
  if (shop.phone) {
    doc.text(`Phone: ${shop.phone}`, 14, y);
    y += 6;
  }

  y += 4;
  doc.setFontSize(13);
  doc.text(orderNumber ? `Order List — ${orderNumber}` : "Order List", 14, y);
  y += 7;
  doc.setFontSize(9);
  doc.text(`Date: ${new Date().toLocaleDateString("en-IN")}`, 14, y);
  y += 8;

  autoTable(doc, {
    startY: y,
    head: [["#", "Category", "Item", "Qty"]],
    body: rows.map((r) => [String(r.sno), r.category, r.item, String(r.quantity)]),
    styles: { fontSize: 9, cellPadding: 3 },
    headStyles: { fillColor: [15, 23, 42], textColor: [244, 185, 66] },
    columnStyles: {
      0: { cellWidth: 12 },
      1: { cellWidth: 38 },
      3: { cellWidth: 18, halign: "center" }
    }
  });

  const footerY = (doc as jsPDF & { lastAutoTable?: { finalY: number } }).lastAutoTable?.finalY ?? y + 20;
  doc.setFontSize(8);
  doc.setTextColor(120);
  doc.text("Generated by EWC ERP SYSTEM", 14, footerY + 10);

  const slug = orderNumber ? orderNumber.replace(/\s+/g, "-") : "draft";
  doc.save(`order-list-${slug}.pdf`);
}

export function exportOrderListToDoc(
  rows: OrderListExportRow[],
  shop: ShopHeader,
  orderNumber?: string
) {
  const title = orderNumber ? `Order List — ${orderNumber}` : "Order List";
  const tableRows = rows
    .map(
      (r) =>
        `<tr>
          <td style="padding:6px;border:1px solid #ccc;text-align:center">${r.sno}</td>
          <td style="padding:6px;border:1px solid #ccc">${escapeHtml(r.category)}</td>
          <td style="padding:6px;border:1px solid #ccc">${escapeHtml(r.item)}</td>
          <td style="padding:6px;border:1px solid #ccc;text-align:center">${r.quantity}</td>
        </tr>`
    )
    .join("");

  const html = `<!DOCTYPE html>
<html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:w="urn:schemas-microsoft-com:office:word">
<head><meta charset="utf-8"><title>${escapeHtml(title)}</title></head>
<body style="font-family:Calibri,Arial,sans-serif;margin:24px;color:#111">
  <h1 style="margin:0 0 8px;font-size:22px">${escapeHtml(shop.shopName)}</h1>
  ${shop.address ? `<p style="margin:0 0 4px;font-size:12px">${escapeHtml(shop.address)}</p>` : ""}
  ${shop.phone ? `<p style="margin:0 0 16px;font-size:12px">Phone: ${escapeHtml(shop.phone)}</p>` : "<p style='margin:0 0 16px'></p>"}
  <h2 style="margin:0 0 6px;font-size:16px">${escapeHtml(title)}</h2>
  <p style="margin:0 0 14px;font-size:11px;color:#444">Date: ${new Date().toLocaleDateString("en-IN")}</p>
  <table style="border-collapse:collapse;width:100%;font-size:12px">
    <thead>
      <tr style="background:#0f172a;color:#f4b942">
        <th style="padding:8px;border:1px solid #ccc;width:40px">#</th>
        <th style="padding:8px;border:1px solid #ccc">Category</th>
        <th style="padding:8px;border:1px solid #ccc">Item</th>
        <th style="padding:8px;border:1px solid #ccc;width:60px">Qty</th>
      </tr>
    </thead>
    <tbody>${tableRows}</tbody>
  </table>
  <p style="margin-top:20px;font-size:10px;color:#666">Generated by EWC ERP SYSTEM</p>
</body></html>`;

  const blob = new Blob(["\ufeff", html], { type: "application/msword" });
  const slug = orderNumber ? orderNumber.replace(/\s+/g, "-") : "draft";
  saveAs(blob, `order-list-${slug}.doc`);
}

function escapeHtml(value: string) {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}
